config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :product_locations
  resources :order_rows
  resources :reviews
  resources :products
  resources :warehouses
  resources :orders
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order_row.rb
class OrderRow < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/controllers/order_rows_controller.rb
class OrderRowsController < ApplicationController
  before_action :set_order_row, only: %i[ show edit update destroy ]

  # GET /order_rows or /order_rows.json
  def index
    @order_rows = OrderRow.all
  end

  # GET /order_rows/1 or /order_rows/1.json
  def show
  end

  # GET /order_rows/new
  def new
    @order_row = OrderRow.new
  end

  # GET /order_rows/1/edit
  def edit
  end

  # POST /order_rows or /order_rows.json
  def create
    @order_row = OrderRow.new(order_row_params)

    
    respond_to do |format|
      begin
        if @order_row.save
          format.html { redirect_to order_row_url(@order_row), notice: "Order row was successfully created." }
          format.json { render :show, status: :created, location: @order_row }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @order_row.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordNotUnique
        format.html { redirect_to root_url(error: "Order row already exists.") }
        format.json { redirect_to root_url, status: :created, location: @order_row }
      end
    end
    
  end

  # PATCH/PUT /order_rows/1 or /order_rows/1.json
  def update
    respond_to do |format|
      if @order_row.update(order_row_params)
        format.html { redirect_to order_row_url(@order_row), notice: "Order row was successfully updated." }
        format.json { render :show, status: :ok, location: @order_row }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_rows/1 or /order_rows/1.json
  def destroy
    @order_row.destroy

    respond_to do |format|
      format.html { redirect_to order_rows_url, notice: "Order row was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_row
      @order_row = OrderRow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_row_params
      params.require(:order_row).permit(:order_id, :product_id, :quantity)
    end
end

app/helpers/order_rows_helper.rb
module OrderRowsHelper
end

app/views/order_rows/_form.html.erb
<%= form_with(model: order_row) do |form| %>
  <% if order_row.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_row.errors.count, "error") %> prohibited this order_row from being saved:</h2>

      <ul>
        <% order_row.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id, :value => params[:order_id], :readonly => true%>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.collection_select(:product_id, Product.all, :id, :name, :prompt => true) %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/order_rows/_order_row.html.erb
<div id="<%= dom_id order_row %>">
  <p>
    <strong>Order:</strong>
    <%= order_row.order_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= order_row.order.user.username %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= order_row.product.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= order_row.quantity %>
  </p>

</div>

app/views/order_rows/edit.html.erb
<h1>Editing order row</h1>

<%= render "form", order_row: @order_row %>

<br>

<div>
  <%= link_to "Show this order row", @order_row %> |
  <%= link_to "Back to order rows", order_rows_path %>
</div>

app/views/order_rows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Order rows</h1>

<%= link_to "New order row", new_order_row_path %> |
<%= link_to "Back to orders", orders_path %>

<div id="order_rows">
  <table class="table">
    <tr>
      <th>Order id</th>
      <th>Username</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Action</th>
    </tr>
    <% @order_rows.each do |order_row| %>
      <tr>
      <td>
        <%= order_row.order_id %>
      </td>
    
      <td>
        <%= order_row.order.user.username %>
      </td>
    
      <td>
        <%= order_row.product.name %>
      </td>
    
      <td>
        <%= order_row.quantity %>
      </td>
    
      <td>
        <%= link_to "Show this order row", order_row %>
      </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/order_rows/new.html.erb
<h1>New order row</h1>
<%= render "form", order_row: @order_row, order_id: params[:order_id] %>

<br>

<div>
  <%= link_to "Back to order rows", order_rows_path %>
</div>

app/views/order_rows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_row %>

<div>
  <%= link_to "Edit this order row", edit_order_row_path(@order_row) %> |
  <%= link_to "Back to orders", orders_path %> |
  <%= link_to "Add product to order", new_order_row_path(order_id: @order_row.order_id) %>

  <%= button_to "Destroy this order row", @order_row, method: :delete %>
</div>