config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :product_locations
  resources :order_rows
  resources :reviews
  resources :products
  resources :warehouses
  resources :orders
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_row
    has_many :product, :through => :order_row

    scope :past_orders, -> (review) { joins("INNER JOIN order_rows ON order_rows.order_id = orders.id").where("order_rows.product_id = ? AND orders.user_id = ?", review.product_id, review.user_id) }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to new_order_row_path(order_id: @order.id) }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:date, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select(:user_id, User.all, :id, :username, :prompt => true) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Date:</strong>
    <%= order.date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= order.user_id %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<%= link_to "New order", new_order_path %>

<div id="orders">
  <table class="table">
    <tr>
      <th>Order id</th>
      <th>Order date</th>
      <th>User</th>
      <th>Products</th>
      <th>Action</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= order.id %>
        </td>
        <td>
          <%= order.date %>
        </td>

        <td>
          <%= order.user.username %>
        </td>

        <td>
          <ul>
            <% order.order_row.each do |order_row| %>
              <li><%= order_row.product.name %></li>
            <% end %>
          </ul> 
        </td>

        <td>
          <%= link_to "Show this order", order %>
        </td>
      </tr>
      
    <% end %>
    </table>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %> |
  <%= link_to "Edit order rows", order_rows_path() %> |
  <%= link_to "Add product to order", new_order_row_path(order_id: @order.id) %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>