config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :product_locations
  resources :order_rows
  resources :reviews
  resources :products
  resources :warehouses
  resources :orders
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product_location.rb
class ProductLocation < ApplicationRecord
    belongs_to :product
    belongs_to :warehouse
end

app/controllers/product_locations_controller.rb
class ProductLocationsController < ApplicationController
  before_action :set_product_location, only: %i[ show edit update destroy ]

  # GET /product_locations or /product_locations.json
  def index
    @product_locations = ProductLocation.all
  end

  # GET /product_locations/1 or /product_locations/1.json
  def show
  end

  # GET /product_locations/new
  def new
    @product_location = ProductLocation.new
  end

  # GET /product_locations/1/edit
  def edit
  end

  # POST /product_locations or /product_locations.json
  def create
    @product_location = ProductLocation.new(product_location_params)

    respond_to do |format|
      if @product_location.save
        format.html { redirect_to product_location_url(@product_location), notice: "Product location was successfully created." }
        format.json { render :show, status: :created, location: @product_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_locations/1 or /product_locations/1.json
  def update
    respond_to do |format|
      if @product_location.update(product_location_params)
        format.html { redirect_to product_location_url(@product_location), notice: "Product location was successfully updated." }
        format.json { render :show, status: :ok, location: @product_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_locations/1 or /product_locations/1.json
  def destroy
    @product_location.destroy

    respond_to do |format|
      format.html { redirect_to product_locations_url, notice: "Product location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_location
      @product_location = ProductLocation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_location_params
      params.require(:product_location).permit(:product_id, :warehouse_id, :quantity)
    end
end

app/helpers/product_locations_helper.rb
module ProductLocationsHelper
end

app/views/product_locations/_form.html.erb
<%= form_with(model: product_location) do |form| %>
  <% if product_location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_location.errors.count, "error") %> prohibited this product_location from being saved:</h2>

      <ul>
        <% product_location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.number_field :product_id %>
  </div>

  <div>
    <%= form.label :warehouse_id, style: "display: block" %>
    <%= form.number_field :warehouse_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_locations/_product_location.html.erb
<div id="<%= dom_id product_location %>">
  <p>
    <strong>Product:</strong>
    <%= product_location.product.name %>
  </p>

  <p>
    <strong>Warehouse:</strong>
    <%= product_location.warehouse.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= product_location.quantity %>
  </p>

</div>

app/views/product_locations/edit.html.erb
<h1>Editing product location</h1>

<%= render "form", product_location: @product_location %>

<br>

<div>
  <%= link_to "Show this product location", @product_location %> |
  <%= link_to "Back to product locations", product_locations_path %>
</div>

app/views/product_locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product locations</h1>

<%= link_to "New product location", new_product_location_path %>

<div id="product_locations">
  <table class="table">
      <tr>
        <th>Product</th>
        <th>Warehouse</th>
        <th>Quantity</th>
        <th>Action</th>
      </tr>
    <% @product_locations.each do |product_location| %>
      <tr>
        <td>
          <%= product_location.product.name %>
        </td>

        <td>
          <%= product_location.warehouse.name %>
        </td>

        <td>
          <%= product_location.quantity %>
        </td>
        <td>
          <%= link_to "Show this product location", product_location %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/product_locations/new.html.erb
<h1>New product location</h1>

<%= render "form", product_location: @product_location %>

<br>

<div>
  <%= link_to "Back to product locations", product_locations_path %>
</div>

app/views/product_locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_location %>

<div>
  <%= link_to "Edit this product location", edit_product_location_path(@product_location) %> |
  <%= link_to "Back to product locations", product_locations_path %>

  <%= button_to "Destroy this product location", @product_location, method: :delete %>
</div>